swagger: "2.0"
info:
  version: "0.0.1"
  title: Ludo
host: localhost:3000
basePath: /
#
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /lobbys:
    x-swagger-router-controller: lobby
    get:
      description: Returns a list of all lobby
      operationId: getLobbys
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Lobbys"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw

definitions:
  Lobby:
    properties:
      id:
        type: number
        description: Unique identifier representing a Lobby
      name:
        type: string
        description: name of a Lobby
      currentPlayers:
        type: number
        description: number of current Players
      maxPlayers:
        type: number
        description: Number of Max Players
      password:
        type: boolean
        description: Tells if a password is needed or not
  Lobbys:
    type: array
    items:
      $ref: '#/definitions/Lobby'
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string